import SwiftUI
import AppFactoryKit
import AppFactoryKitRevenueCat

// ─────────────────────────────────────────────────────────────────────────
// MileageTracker — generated by AppFactoryKit appgen from niche "mileage-tracker".
// Per-app surface = this config + ContentView's feature. Everything that earns
// (onboarding, paywall, subscriptions, funnel) is inherited from the kit.
// ─────────────────────────────────────────────────────────────────────────

// Paste your RevenueCat public SDK key here to go live. Until then the app runs
// on a mock provider so you can preview the real paywall in the simulator.
private let revenueCatKey = "appl_REPLACE_ME"

@MainActor
enum MileageTrackerFactory {
    static func make() -> AppFactory {
        let provider: PurchaseProvider = revenueCatKey == "appl_REPLACE_ME"
            ? MockPurchaseProvider()
            : RevenueCatPurchaseProvider(apiKey: revenueCatKey, entitlementID: "premium")

        let config = AppFactoryConfiguration(
            appName: "MileageTracker",
            purchaseProvider: provider,
            onboarding: OnboardingConfiguration(
                slides: [
                    .init(systemImage: "dollarsign.circle",
                          title: "MileageTracker",
                          message: "Auto-log drives for tax/expense."),
                    .init(systemImage: "chart.line.uptrend.xyaxis",
                          title: "Go Pro",
                          message: "Auto-tracking, IRS reports, unlimited trips.")
                ],
                presentsPaywallOnFinish: true,
                accent: .green
            ),
            paywall: PaywallConfiguration(
                headline: "Unlock MileageTracker Pro",
                subheadline: "Auto-tracking, IRS reports, unlimited trips.",
                benefits: [
                    .init(systemImage: "infinity", title: "Auto-tracking"),
                    .init(systemImage: "bolt.fill", title: "IRS reports"),
                    .init(systemImage: "nosign", title: "Unlimited trips")
                ],
                productIDs: ["mileage-tracker_yearly", "mileage-tracker_weekly"],
                highlightedProductID: "mileage-tracker_yearly",
                ctaTitle: "Continue",
                dismissButtonDelay: 4,
                isDismissable: true,
                termsURL: URL(string: "https://YOURDOMAIN.com/terms"),
                privacyURL: URL(string: "https://YOURDOMAIN.com/privacy"),
                style: PaywallStyle(accent: .green, heroSystemImage: "dollarsign.circle")
            )
        )
        return AppFactory(config)
    }
}

@main
struct MileageTrackerApp: App {
    @StateObject private var factory = MileageTrackerFactory.make()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .appFactoryRoot(factory)
                .tint(.green)
        }
    }
}
